apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-config-app
  namespace: demo-config
  labels:
    app: demo-config-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-config-app
  template:
    metadata:
      labels:
        app: demo-config-app
    spec:
      containers:
      - name: demo-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
